george and accommodation
kamilnapiontek/codeforcesTraining pull request #2
Opened 2023-03-13 20:08 UTC by kamilnapiontek

2023-03-14 10:36 UTC, Y0ucandev requested changes

2023-03-14 10:36 UTC, Y0ucandev commented on codeforces/src/main/java/org/example/georgeAndAccommodation/Dormitory.java
> +        for (Room room : rooms) {
moze da sie to jakos na streama przerobic? 
To i caly for w srodku

2023-03-14 10:36 UTC, Y0ucandev commented on codeforces/src/main/java/org/example/georgeAndAccommodation/Room.java
> +    public Room(int howManyPeopleAccommodated, int maxCapacity) {
skoro klasa pakietowa to nie ma sensu robic publicznego konstruktora, tylko pakietowy

2023-03-14 10:36 UTC, Y0ucandev commented on codeforces/src/test/java/org/example/georgeAndAccommodation/DormitoryTest.java
> +    Dormitory dormitory = new Dormitory();
private

2023-03-16 02:17 UTC, kamilnapiontek commented on codeforces/src/test/java/org/example/georgeAndAccommodation/DormitoryTest.java
> +    Dormitory dormitory = new Dormitory();
widzisz mój nowy PR - fix?

2023-03-16 15:37 UTC, Y0ucandev requested changes

2023-03-16 15:37 UTC, Y0ucandev commented on codeforces/src/main/java/org/example/georgeAndAccommodation/Room.java
> +    public int getAccommodatedPeople() {
public nie ma sensu jezeli klasa jest package private. Bo i tak to nie bedzie public. Bo co kolwiek jest w srodku klasy jest package private z automatu 
![image](https://user-images.githubusercontent.com/112213953/225668816-0640061d-268d-4b40-93df-d67a3bab5e2b.png)

2023-03-16 15:37 UTC, Y0ucandev commented on codeforces/src/test/java/org/example/georgeAndAccommodation/DormitoryTest.java
> +
zbedna pusta linia

2023-03-16 15:37 UTC, Y0ucandev commented on codeforces/src/test/java/org/example/georgeAndAccommodation/DormitoryTest.java
> +    private Dormitory dormitory = new Dormitory();
final moze byc bo raczej nie zmieniasz jej stanu

2023-03-16 15:37 UTC, Y0ucandev commented on codeforces/src/test/java/org/example/georgeAndAccommodation/DormitoryTest.java
> +    Dormitory dormitory = new Dormitory();
zrobilem review wiec widze

2023-03-21 11:16 UTC, Y0ucandev requested changes

2023-03-21 11:16 UTC, Y0ucandev commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/intellij,java
zadzialal Ci ten gitIgnore? bo ja widze ze masa smietnika probuje byc dodana do repo

2023-03-21 14:05 UTC, Y0ucandev approved these changes

2023-03-21 14:05 UTC, merged