jump game
kamilnapiontek/codeforcesTraining pull request #5
Opened 2023-04-21 19:35 UTC by kamilnapiontek

2023-04-21 21:35 UTC, Y0ucandev requested changes

2023-04-21 21:35 UTC, Y0ucandev commented on codeforces/src/main/java/org/example/jumpGame/JumpGame.java
> +        int difference = 0;
albo inicjalizuj wszystko albo nic. int ma domyslna wartosc =  0

2023-04-21 21:35 UTC, Y0ucandev commented on codeforces/src/main/java/org/example/jumpGame/JumpGame.java
> +        while (listToJump.get(currentIndex) + currentIndex < listToJump.size() - 1) {
zwin to do funkcji bo bardzo skomplikowany jest ten warunek, az sie czytac tego nie chce :D

2023-04-21 21:35 UTC, Y0ucandev commented on codeforces/src/main/java/org/example/jumpGame/JumpGame.java
> +
zbedna pusta linia

2023-04-21 21:35 UTC, Y0ucandev commented on codeforces/src/test/java/org/example/jumpGame/JumpGameTest.java
> +    private JumpGame jumpGame = new JumpGame();
final

2023-04-24 14:07 UTC, kamilnapiontek commented on codeforces/src/main/java/org/example/jumpGame/JumpGame.java
> +        int difference = 0;
![image](https://user-images.githubusercontent.com/43855312/234020687-4cb9d199-b359-438d-b1f9-42eaa65fcd03.png)
Ja tutaj mam oddzielone zmienne, które są zerowane i inicjalizowane w pętli od tych, które tylko inkrementuje, mogę im tam wszystkim wrzucić zero na starcie, ale później wykonywać będę 2 razy tą samą operacje. Także nie wiem co jest lepsze

2023-04-26 08:17 UTC, Y0ucandev approved these changes

2023-04-26 08:18 UTC, merged